---
title: "About Me"
output:
  rmarkdown::html_document:
    theme: lumen
---

Welcome! I'm a second year graduate student at the University of Massachusetts Amherst in the [Organismic and Evolutionary Biology program](https://gpls.cns.umass.edu/oeb) working with [Dr. David Sela](https://www.selalab.org/) in the Food Science Department. I'm broadly interested in the evolution of inter-individual differences in human milk composition. Also, how maternal genetics and environmental exposures influence the development of the infant gut microbiome. I use molecular genetics to investigate carbohydrate scavenging in the infant gut commensal Bifidobacterium longum subsp. infantis. I also use a simplified in vitro model of the distal gut microbiome to study how host-indigestible carbohydrates modulate fecal communities.

In my free time I enjoy bouldering, watching horror movies or documentaries, gardening, reading science non-fiction, baking, watercolor painting, and playing board games!

## About My Funding 

>- For my first and last year, I've been generously funded by the Graduate School as a [Spaulding-Smith Fellow](https://www.umass.edu/graduate/inclusion/spaulding-smith-fellows).
>- I am also internally funded by The [Predissertation Research Grant](https://www.umass.edu/graduate/funding/internal-funding) to develop strain-specific RT-PCR primers in order to investigate competitive interactions among numerous B. infantis strains. 
>- Stay tuned for more! 
